### PR TITLE
SmartCity_Traffic_Light_Application

### PR DESCRIPTION
**Pull request by JayeshRajam**
https://user-images.githubusercontent.com/87312836/127764668-d68228e3-d91e-4c64-93e7-b8630d80d33b.mp4

Edge-Impulse based City Traffic Light application using Himax WE-I Plus Board, which detects whether a car has crossed the stop line or not, and also simultaneously uses SparkFun's Qwiic sensors to obtain CO2, TVOC and Humidity data.
Have used Edge-Impulse and Docker

### CODE REVIEW

**Comment by JayeshRajam** [comment]
>  outputdemo.mp4 
> Edge-Impulse based City Traffic Light application using Himax WE-I Plus Board, which detects whether a car has crossed the stop line or not, and also simultaneously uses SparkFun's Qwiic sensors to obtain CO2, TVOC and Humidity data.
> Have used Edge-Impulse and Docker

Have executed a prototype of the application, using a Hotwheels car.

**Comment by bigcat-himax** [comment]
Please remove unnecessary .o files, thanks.

**Comment by JayeshRajam** [comment]
Done! Please check now.

**Comment by bigcat-himax** [comment]
can you please help to add notification about chmod for image_gen_gnu ?
we encounter "../make-image.sh: 29: ./image_gen_gnu: Permission denied" error while following your steps.

**Comment by JayeshRajam** [comment]
Hey! was the error encountered in the Docker steps. If so, maybe running the docker commands with sudo one by one can resolve this.
This is the guide I followed for docker installation on Ubuntu (in order to avoid version conflicts): https://docs.docker.com/engine/install/ubuntu/
I have not faced any such permission error, I also build the application from a different system too. Any image describing the error you can please send so that we can figure it out.

**Comment by bigcat-himax** [comment]
> Hey! was the error encountered in the Docker steps. If so, maybe running the docker commands with sudo one by one can resolve this.
> This is the guide I followed for docker installation on Ubuntu (in order to avoid version conflicts): https://docs.docker.com/engine/install/ubuntu/
> I have not faced any such permission error, I also build the application from a different system too. Any image describing the error you can please send so that we can figure it out.

yes, error happen when following command 
 sudo docker run --rm -it -v $PWD:/app:delegated himax-build-gnu /bin/bash -c "cd build-gnu && make -j && sh ../make-image.sh GNU"

and the error message is:
/opt/arc_gnu/arc_gnu_ei_prebuilt_minimal_elf32_le_linux_install/bin/../lib/gcc/arc-elf32/10.2.0/../../../../arc-elf32/bin/ld: total time in link: 0.266359
[100%] Built target app.elf
GNU Image Gen Tool
../make-image.sh: 29: ./image_gen_gnu: Permission denied

**Comment by JayeshRajam** [comment]
Screenshot 2021-07-28 005238

**Comment by JayeshRajam** [comment]
image
I replaced the make_image.sh file with one from my local computer also tested it. It works. Check now.

**Comment by bigcat-himax** [comment]
Screenshot from 2021-08-06 21-48-02

clone again and same error here, i think the reason is because image_gen_gnu need +x mode to be executed
  
Screenshot from 2021-08-06 21-45-00

**Comment by JayeshRajam** [comment]
Hi @bigcat-himax, you were correct, when transferred to other PC , permissions Issues are faced. Also you were correct about the +x mode.
I ran two commands (going in image_gen_linux)
**chmod u+x image_gen_gnu
chmod u+x sign_tool** 
(came one dir back and ran the sudo docker run --rm -it -v $PWD:/app:delegated himax-build-gnu /bin/bash -c "cd build-gnu && make -j && sh ../make-image.sh GNU" command)
and it worked. Thank you for the help.

**Comment by JayeshRajam** [comment]
So, should I add these chmod commands in Readme file or make another commit with updated files(I am not sure whether it'll do it) ?

**Comment by bigcat-himax** [comment]
> So, should I add these chmod commands in Readme file or make another commit with updated files(I am not sure whether it'll do it) ?

It would be great if you can commit with updated files, thanks.

**Comment by bigcat-himax** [comment]
by the way, please copy License file into your project, you can find them in the example template.

**Comment by JayeshRajam** [comment]
**Done!** I had to make 2 commits so as to remove and add the upgraded files as modified was not available.
Now, I guess everything is done with no errors. Looking forward to merger of pull request.

**Comment by bigcat-himax** [comment]
seems +x mode to github file makes no effects, still see permission error
image_gen_gnu_err

can you add chmod commands in Readme file instead? i see following files will need +x permission 
- image_gen_gnu
- image_gen
- sign_tool
sign_tool_err

**Comment by JayeshRajam** [comment]
@bigcat-himax I updated the readme file. Check

**Pull request merged**
